<?php
/**
*
* @package phpBB Extension - Digests
* @copyright (c) 2016 Mark D. Hamill (mark@phpbbservices.com)
* @license http://opensource.org/licenses/gpl-2.0.php GNU General Public License v2
* @french localisation by Philippe Bonnaure - Mac V.F - www.macvf.fr
*
*/

if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

global $phpbb_container;

$config = $phpbb_container->get('config');
$helper = $phpbb_container->get('phpbbservices.digests.common');

$lang = array_merge($lang, array(
	'DIGESTS_ALL'											=> 'Tous',
	'DIGESTS_ALL_ALLOWED_FORUMS'							=> 'Tous les forums autorisés',
	'DIGESTS_ALL_SUBSCRIBED'								=> '%d membres au total ont été abonnés en masse à la réception du résumé',
	'DIGESTS_ALL_UNSUBSCRIBED'								=> '%d membres au total ont été désabonnés en masse à la réception du résumé',
	'DIGESTS_BALANCE_LOAD'									=> 'Équilibrage de la charge',
	'DIGESTS_BASED_ON'										=> '(Basé sur %s UTC)',
	'DIGESTS_CURRENT_VERSION_INFO'							=> 'Vous exécutez la version <strong>%s</strong>.',
	'DIGESTS_CUSTOM_STYLESHEET_PATH'						=> 'Chemin d\'accès à la feuille de style personnalisée',
	'DIGESTS_CUSTOM_STYLESHEET_PATH_EXPLAIN'				=> 'Ce réglage ne s\'applique que si l\'option Activer la feuille de style personnalisée est activée. Si elle est activée, cette feuille de style sera appliquée à tous les résumés. Le chemin d\'accès doit être un chemin d\'accès relatif à votre répertoire de styles phpBB qui doit normalement se trouver dans le sous-répertoire theme. Nota : vous êtes responsables de la création de la feuille de style et de son placement dans un fichier ayant pour nom celui saisi ici à l\'endroit approprié sur votre serveur. Exemple: prosilver/theme/digest_stylesheet.css. Pour des informations relatives à la création de feuilles de style, cliquez <a href="http://www.w3schools.com/css/">ici</a>.',
	'DIGESTS_COLLAPSE'										=> 'Réduire',
	'DIGESTS_DEFAULT'										=> 'S\'abonner en utilisant les valeurs par défaut',
	'DIGESTS_ENABLE_AUTO_SUBSCRIPTIONS'						=> 'Activer les abonements automatiques',
	'DIGESTS_ENABLE_AUTO_SUBSCRIPTIONS_EXPLAIN'				=> 'Si vous souhaitez que les nouveaux membres du forum reçoivent automatiquement les résumés, sélecionnez Oui. Les réglages par défaut du résumé s\'appliqueront automatiquement. (Ils sont définis dans les réglages du résumé par défaut de l\'utilisateur). L\'activation de cette option ne va <em>pas</em> créer d\'abonnement pour les personnes qui ne sont pas abonnées, les membres inactifs ou les nouveaux membres qui choisissent de ne pas recevoir un résumé pendant l\'enregistrement. Vous pouvez définir cela individuellement en utilisant la fonction Éditer les abonnés, ou de manière globale avec l\'option Abonnement/Désabonnement en masse.',
	'DIGESTS_ENABLE_CUSTOM_STYLESHEET'						=> 'Activer la feuille de style personnalisée',
	'DIGESTS_ENABLE_CUSTOM_STYLESHEET_EXPLAIN'				=> 'Lorsque cette option n\'est pas activée, la feuille de style par défaut utilisée est celle sélectionnée dans le profil de l\'utilisateur pour la génération HTML de leurs résumés.',
	'DIGESTS_ENABLE_LOG'									=> 'Écrire toutes les actions du résumé dans le journal de l\'administrateur',
	'DIGESTS_ENABLE_LOG_EXPLAIN'							=> 'Lorsque l\'option est activée, toutes actions de résumés seront inscrites sur le journal de l\'admin (que l\'on trouve dans l\'onglet Maintenance). Pratique pour répondre à des questions relatives au résumé dans la mesure où il indique ce qu\'à fait le générateur de mails de résumé à fait, quand et pour quels abonnés. Son activation va rapidement générer de longs journaux d\'administration dans la mesure où deux entrées seront écrites toutes les heures dans le journal. Nota : les erreurs, les exceptions et les alertes sont toujours inscrites dans le journal.',
	'DIGESTS_ENABLE_SUBSCRIBE_UNSUBSCRIBE'					=> 'Activer l\'abonnement ou le désabonnement en masse',
	'DIGESTS_ENABLE_SUBSCRIBE_UNSUBSCRIBE_EXPLAIN'			=> 'Si vous indiquez Oui, lorsque vous cliquez Envoyer, une action d\'abonnement ou de désabonnement en masse va survenir. Activer avec précaution !',
	'DIGESTS_EXCLUDE_FORUMS'								=> 'Toujours exclure les forums suivants',
	'DIGESTS_EXCLUDE_FORUMS_EXPLAIN'						=> 'Saisissez le forum_id des forums qui ne doivent pas figurer dans le résumé. Séparez les forums_id par des virgules. En indiquant 0, aucun forum ne sera exclu. Pour déterminer le forum_id d\'un forum, observez la valeur du paramètre "f" dans le champ de l\'URL. C\'est le forum_id. Exemple: http://www.example.com/phpBB3/viewforum.php?f=1. Ne pas utiliser de forum_ids qui correspondent à des catégories. <i>Ce réglage est ignoré si l\'option Sujets cochés seulement est cochée par l\'utilisateur.</i>',
	'DIGESTS_EXPAND'										=> 'Agrandir',
	'DIGESTS_FORMAT_FOOTER' 								=> 'Format du résumé',
	'DIGESTS_FROM_EMAIL_ADDRESS'							=> 'Depuis l\'adresse électronique',
	'DIGESTS_FROM_EMAIL_ADDRESS_EXPLAIN'					=> 'Lorsque les utilisateurs recoivent un résumé, cette adresse électronique va s\'afficher dans le champ "De". S\'il est laissé vide, l\'adresse électronique de votre Forum sera utilisé par défaut. Faites attention lorsque vous utilisez une adresse électronique dont le domaine ne correspond pas à celui sur lequel est hébergé votre Forum, dans la mesure où votre serveur de courriels ou le serveur de courriels des utilisateurs pourra interprêter le courriel comme étant du spam.',
	'DIGESTS_FROM_EMAIL_NAME'								=> 'Nom de l\'expéditeur du courriel',
	'DIGESTS_FROM_EMAIL_NAME_EXPLAIN'						=> 'C\'est le nom qui apparaîtra en clair dans le champ DE dans le logiciel de courriel client de l\'utilisateur. Si le champ est laissé vide il s\'identifera en tant que robot de votre forum.',
	'DIGESTS_HAS_UNSUBSCRIBED'								=> 'S\'est désabonné',
	'DIGESTS_HOUR_SENT'										=> 'Heure d\'envoi (basé sur %s UTC)',
	'DIGESTS_IGNORE'										=> 'Ignorer les actions globales',
	'DIGESTS_ILLOGICAL_DATE'								=> 'Votre date de simulation n\'est pas cohérente, comme 31 Février. Veuillez la corriger et Envoyez à nouveau.',
	'DIGESTS_INCLUDE_ADMINS'								=> 'Inclure les administrateurs',
	'DIGESTS_INCLUDE_ADMINS_EXPLAIN'						=> 'Permet d\'abonner ou de désabonner des administrateurs en plus des utilisateurs normaux.',
	'DIGESTS_INCLUDE_FORUMS'								=> 'Toujours inclure ces forums',
	'DIGESTS_INCLUDE_FORUMS_EXPLAIN'						=> 'Saisissez le forum_id des forums qui doivent figurer dans le résumé. Séparez les forum_id par des virgules. En indiquant 0, aucun forum ne sera inclus. Pour déterminer le forum_id d\'un forum, observez la valeur du paramètre "f" dans le champ de l\'URL. C\'est le forum_id. Exemple: http://www.example.com/phpBB3/viewforum.php?f=1. Ne pas utiliser de forum_ids qui correspondent à des catégories. <i>Ce réglage est ignoré si l\'option Sujets cochés seulement est cochée par l\'utilisateur.</i>',
	'DIGESTS_LAST_SENT'										=> 'Dernier résumé envoyé',
	'DIGESTS_LIST_USERS' 								=> array(
																	1	=>	'1 Utilisateur',
																	2	=>	'%d Utilisateurs',
																),
	'DIGESTS_MAILER_NOT_RUN'								=> 'Le générateur de courriels n\'a pas été lancé car il n\'est pas activé.',
	'DIGESTS_MAILER_RAN_SUCCESSFULLY'						=> 'Le générateur de courriels a été lancé avec succès.',
	'DIGESTS_MAILER_RAN_WITH_ERROR'							=> 'Une erreur est survenue avec le générateur de courriels. Un ou plusieurs résumés ont pu être générés avec succès.',
	'DIGESTS_MAILER_SPOOLED'								=> 'Tous les résumés créés pour la date et l\'heure ont été enregistrés dans le répertoire cache/phpbbservices/digests.',
	'DIGESTS_MAX_CRON_HOURS'								=> 'Nombre d\'heures maximum d\'exécution par le générateur de courriels',
	'DIGESTS_MAX_CRON_HOURS_EXPLAIN'						=> 'Réglez cette valeur sur 0 (zéro) afin de traiter toutes les heures, les résumés dans la file d\'attente, lorsque générateur de mail est lancé. Cependant, si vous disposez d\'un <strong>hébergement partagé</strong> le lancement du générateur de courriel peut lui faire atteindre ses limites et entraîner une erreur. Cela ne risque d\'arriver que si vous avez de nombreux abonnés et que le traffic sur votre forum est élevé. La mise en place d\'un <a href="https://wiki.phpbb.com/PhpBB3.1/RFC/Modular_cron#Use_system_cron">service cron</a> est la solution la plus simple pour réduire ce risque et de vous assurer que vos résumés arrivent en temps et en heure.',
	'DIGESTS_MAX_ITEMS'										=> 'Nombre maximum de posts autorisés dans un résumé',
	'DIGESTS_MAX_ITEMS_EXPLAIN'								=> 'Pour des raisons de performances, vous pouvez avoir besoin de définir une limite absolue quant au nombre de posts dans un résumé. Si vous indiquez 0 (zéro) le résumé pourra avoir une taille illimitée. Vous pouvez utiliser tout nombre entier de votre choix dans ce champ. Veuillez noter qu\'un résumé est contraint par le nombre de posts dans le type de résumé demandé (journalier, hebdomadaire ou mensuel) ainsi que d\'autres critères définis par l\'utilisateur.',
	'DIGESTS_MAIL_FREQUENCY' 								=> 'Fréquence des résumés',
	'DIGESTS_MIGRATE_UNSUPPORTED_VERSION'					=> 'Les mises à niveau des modifications des résumés (pour phpBB 3.0) sont prises en charge depuis la version 2.2.6 et suivantes. Vous utilisez la version %s. L\extension ne peut pas être déplacée ou installée. Veuillez consulter l\'aide sur le forum de support de phpbb.com.',
	'DIGESTS_NEVER_VISITED'									=> 'Jamais visité',
	'DIGESTS_NO_DIGESTS_SENT'								=> 'Aucun résumé envoyé',
	'DIGESTS_NO_MASS_ACTION'								=> 'Aucune action n\'a été réalisée, car vous n\'avez pas activé la fonction',
	'DIGESTS_NOTIFY_ON_ADMIN_CHANGES'						=> 'Notifier un membre par courriel d\'une modification du résumé par un administrateur',
	'DIGESTS_NOTIFY_ON_ADMIN_CHANGES_EXPLAIN'				=> 'Éditer les abonnés, Équilibrage de la charge et Abonnement/Désabonnement en masse permettent à l\'administrateur de modifier les réglages du résumé d\'un utilisateur. Si oui, un courriel sera envoyé aux abonnés lorsqu\'un aspect de leur abonnement est modifié par un administrateur.',
	'DIGESTS_PMS_MARK_READ'									=> 'Marquer mes messages privés comme lus s\'ils sont dans le résumé',
	'DIGESTS_RANDOM_HOUR'									=> 'Heure aléatoire',
	'DIGESTS_REBALANCED'									=> 'Pendant l\'équilibrage, %d résumés d\'abonné au total ont eu leur heure d\'envoi de résumé modifié.',
	'DIGESTS_REFRESH'										=> 'Actualiser',
	'DIGESTS_REGISTRATION_FIELD'							=> 'Autoriser les utilisateurs à s\'abonner aux résumés une fois enregistrés',
	'DIGESTS_REGISTRATION_FIELD_EXPLAIN'					=> 'Si l\'option est activée, une fois enregistré les utilisateurs ont la possibilité de recevoir des résumés avec les réglages par défaut du forum. Cette option n\'apparaît pas si l\'abonnement automatique est activé.',
	'DIGESTS_REPLY_TO_EMAIL_ADDRESS'						=> 'Adresse de réponse au couriel',
	'DIGESTS_REPLY_TO_EMAIL_ADDRESS_EXPLAIN'				=> 'Lorsque les utilisateurs reçoivent un résumé, cette adresse électronique apparaîtra dans le champ REPONDRE. Si le champ est laissé vide, l\'adresse électronique de contact de votre forum sera utilisé. Faites attention lorsque vous utilisez une adresse électronique dont le domaine ne correspond pas à celui sur lequel est hébergé votre Forum, dans la mesure où votre serveur de courriels ou le serveur de courriels des utilisateurs pourra interprêter le courriel comme étant du spam.',
	'DIGESTS_RESET_CRON_RUN_TIME'							=> 'Réinitialiser le générateur de courriels',
	'DIGESTS_RESET_CRON_RUN_TIME_EXPLAIN'					=> 'Si cette option est réinitialisée, lorsque le générateur de courriels est à nouveau exécuté il crée des résumés pour l\'heure courante seulement. Tous les résumés dans la file d\'attente sont supprimés. La réinitialisation peut être utile lorsque vous avez terminé de tester les résumés ou si les crons phpBB n\'ont pas fonctionné depuis longtemps.',
	'DIGESTS_RUN_TEST'										=> 'Lancer le générateur de courriels',
	'DIGESTS_RUN_TEST_CLEAR_SPOOL'							=> 'Effacer le répertoire cache/phpbbservices/digests',
	'DIGESTS_RUN_TEST_CLEAR_SPOOL_ERROR'					=> 'Impossible de supprimer tous les fichiers dans le répertoire cache/phpbbservices/digests. Cela est peut-être dû à des problèmes de permissions. Les permissions de fichier du répertoire doivent être réglées sur écriture publique (777 sur les systèmes Unix).',
	'DIGESTS_RUN_TEST_CLEAR_SPOOL_EXPLAIN'					=> 'Si vous indiquez Oui, tous les fichiers dans le répertoire cache/phpbbservices/digests seront effacés. C\'est une bonne chose à faire pour s\'assurer que les précédents résumés ne soient plus accessibles. Cette action est réalisée avant que tout nouveau résumé ne soit écrit dans ce répertoire.',
	'DIGESTS_RUN_TEST_DAY'									=> 'Simulation du jour dans le mois',
	'DIGESTS_RUN_TEST_DAY_EXPLAIN'							=> 'Saisissez un nombre entier entre 1 et 31. Si l\'année, le mois et le jour sont dans le futur aucun résumé ne sera généré. N\'utilisez pas un jour qui logiquement n\'appartient pas au mois, comme le 31 Février.',
	'DIGESTS_RUN_TEST_EMAIL_ADDRESS'						=> 'Tester l\'adresse électronique',
	'DIGESTS_RUN_TEST_EMAIL_ADDRESS_EXPLAIN'				=> 'Si une adresse électronique est indiquée dans ce champ, tous les résumés seront envoyés à cette adresse électronique à l\'heure prévue au lieu de l\'adresse électronique de contact du forum.',
	'DIGESTS_RUN_TEST_HOUR'									=> 'Simulation de l\'heure',
	'DIGESTS_RUN_TEST_HOUR_EXPLAIN'							=> 'Les résumés seront envoyés comme pour l\'heure spécifiée. L\'heure est basée sur le fuseau horaire de votre forum (' . $helper->make_tz_offset($config['board_timezone']) . ' UTC). Si elle est dans le futur aucun résumé ne sera généré. Saisissez un nombre entier de 0 à 23.',
	'DIGESTS_RUN_TEST_MONTH'								=> 'Simulation du mois',
	'DIGESTS_RUN_TEST_MONTH_EXPLAIN'						=> 'Saisissez un nombre entier de 1 à 12. Normalement la valeur doit être réglée avec celle du mois courant. Si l\'année et le mois sont dans le futur aucun résumé ne sera généré.',
	'DIGESTS_RUN_TEST_OPTIONS'								=> 'Exécuter les options de date et d\'heure.',
	'DIGESTS_RUN_TEST_SEND_TO_ADMIN'						=> 'Envoyer tous les résumés à l\'adresse électronique spécifiée',
	'DIGESTS_RUN_TEST_SEND_TO_ADMIN_EXPLAIN'				=> 'Si vous souhaitez envoyer les résumés pendant le test, tous les résumés seront envoyés à l\'adresse spécifiée dans le champ ci-dessous. Si vous indiquez Oui, mais qu\'aucune adresse n\'a été spécifiée, l\'adresse électronique de contact du forum (' . $config['board_email']. ') sera utilisée. <em>Attention</em> : Certains serveurs de courriels pourraient interpréter ce grand volume de mails envoyés sur une brève période de temps et à une même adresse comme étant du spam ou ayant un contenu inaproprié. À activer avec précaution. Si vous indiquez Non, les résumés seront envoyés aux abonnés, ce qui pourrait les perturber.',
	'DIGESTS_RUN_TEST_SPOOL'								=> 'Écrire les résultats dans des fichiers au lieu de les envoyer par courriels',
	'DIGESTS_RUN_TEST_SPOOL_EXPLAIN'						=> 'Évite que les résumés ne soient envoyés par courriels. À la place chaque résumé est écrit dans un fichier du répertoire cache/phpbbservices/digests avec des noms de fichier dans le format suivant : nom d\'utilisateur-aaaa-mm-jj-hh.html ou nom d\'utilisateur-aaaa-mm-jj-hh.txt. (Fichier avec un suffixe .txt sont des résumés textuel uniquement.) aaaa indique l\'année, mm le mois, jj le jour dans le mois et hh l\'heure. La Date et l\'heure dans le nom du fichier sont basés sur le temps coordonné universel (UTC). Si vous simulez un autre jour ou une autre heure pour envoyer les résumés à l\'aide des champs ci-dessous, les noms de fichier utiliseront cette date et cette heure. Ces résumés peuvent être visualisés si vous indiquez le bon URL.',
	'DIGESTS_RUN_TEST_TIME_USE'								=> 'Simuler mois et heure, ou jour de la semaine et heure pour envoyer les résumés',
	'DIGESTS_RUN_TEST_TIME_USE_EXPLAIN'						=> 'Si le réglage est Oui, les éléments de simulation ci-dessous seront utilisés pour envoyer un résumé, comme s\'il s\'agissait du mois, de l\'heure et du jour de la semaine spécifié. Si Non, la date et l\'heure actuelle seront utilisées.',
	'DIGESTS_RUN_TEST_YEAR'									=> 'Simulation de l\'année',
	'DIGESTS_RUN_TEST_YEAR_EXPLAIN'							=> 'Les années de 2000 à 2030 sont autorisées. Normalement le réglage doit correspondre à l\'année courante. Si l\'année est dans le futur, aucun résumé ne sera généré.',
	'DIGESTS_SEARCH_FOR_MEMBER'								=> 'Rechercher des membres',
	'DIGESTS_SEARCH_FOR_MEMBER_EXPLAIN'						=> 'Saisissez tout ou partie du nom du membre à rechercher puis pressez Actualiser. Laissez vide pour voir tous les membres. Les recherches ne sont pas sensibles à la casse.',
	'DIGESTS_SELECT_FORUMS_ADMIN_EXPLAIN'					=> 'Seuls les forums que l\'utilisateur est autorisé à lire sont affichés dans la liste. Si vous souhaitez donner aux utilisateurs des accès à d\'autres forums non affichés ici, étendez leur permission d\'utilisateur du forum ou de groupe. Notez que vous pouvez aussi ajuster les forums qui apparaissent dans leur résumé, si leur type de résumé est "Aucun" aucun résumé ne sera envoyé.',
	'DIGESTS_SHOW'											=> 'Afficher',
	'DIGESTS_SHOW_EMAIL'									=> 'Afficher l\'adresse électronique dans le journal',
	'DIGESTS_SHOW_EMAIL_EXPLAIN'							=> 'Si cette option est activée, l\'adresse électronique de l\'abonné est affichée dans les entrées du journal d\'administration avec le nom d\'utilisateur de l\'abonné. Cela peut être utile en cas de problème avec le générateur de courriels.',
	'DIGESTS_SORT_ORDER'									=> 'Ordre de classement',
	'DIGESTS_STOPPED_SUBSCRIBING'							=> 'Est désabonné',
	'DIGESTS_SUBSCRIBE_EDITED'								=> 'Les réglages d\'abonnement de votre résumé ont été édités',
	'DIGESTS_SUBSCRIBE_SUBJECT'								=> 'Vous avez été abonné pour recevoir des résumés par courriel',
	'DIGESTS_SUBSCRIBE_ALL'									=> 'Abonner tout le monde',
	'DIGESTS_SUBSCRIBE_ALL_EXPLAIN'							=> 'Si vous dites non, tout le monde sera désabonné.',
	'DIGESTS_SUBSCRIBE_LITERAL'								=> 'S\'abonner',
	'DIGESTS_SUBSCRIBED'									=> 'Abonné',
	'DIGESTS_SUBSCRIBERS' 		=> 'Abonnés',	
	'DIGESTS_TIME_ZONE'										=> 'Fuseau horaire',
	'DIGESTS_TIME_ZONE_EXPLAIN'								=> 'Les fonctions Éditer les abonnés et Équilibrage de la charge affichent les heures auxquelles les résumés sont envoyés. Si vous y définissez un fuseau horaire en particulier, les heures d\'envoi seront translatées dans le fuseau horaire que vous avez défini ici. Le fuseau horaire initial est celui du forum. Les valeurs doivent être des entiers compris entre -12 et +12, 0 étant l\'UTC.',
	'DIGESTS_UNSUBSCRIBE'									=> 'Se désabonner',
	'DIGESTS_UNSUBSCRIBE_SUBJECT'							=> 'Vous avez été désabonnés de la réception de courriels de résumés',
	'DIGESTS_UNSUBSCRIBED'									=> 'N\'est pas abonné',
	'DIGESTS_USER_DIGESTS_ATTACHMENTS'						=> 'Réglage par défaut pour afficher les pièces jointes',
	'DIGESTS_USER_DIGESTS_BLOCK_IMAGES'						=> 'Réglage par défaut pour bloquer les images',
	'DIGESTS_USER_DIGESTS_CHECK_ALL_FORUMS'					=> 'Sélectionner tous les forums par défaut',
	'DIGESTS_USER_DIGESTS_FILTER_TYPE'						=> 'Types de posts par défaut dans les résumés',
	'DIGESTS_USER_DIGESTS_MAX_DISPLAY_WORDS'				=> 'Nombre maximum de mots à afficher par défaut dans un post',
	'DIGESTS_USER_DIGESTS_MAX_DISPLAY_WORDS_EXPLAIN'		=> 'Saisir -1 pour afficher tout le texte du post par défaut. La valeur zéro (0) signale que l\'utilisateur ne veut voir aucun texte de post.',
	'DIGESTS_USER_DIGESTS_MAX_POSTS'						=> 'Nombre maximum de post par défaut dans un résumé',
	'DIGESTS_USER_DIGESTS_MAX_POSTS_EXPLAIN'				=> 'Si le réglage est à zéro, il autorisera un nombre illimité de posts. Veuillez noter que l\'option pas de résumé ne contiendra jamais plus de posts que le nombre de posts maximum autorisés (Voir les réglages généraux).',
	'DIGESTS_USER_DIGESTS_MIN_POSTS'						=> 'Nombre de mots minimum par défaut dans un post pour qu\'il puisse apparaître dans un résumé',
	'DIGESTS_USER_DIGESTS_MIN_POSTS_EXPLAIN'				=> 'Saisir zéro (0) pour autoriser un nombre quelconque de mots par post.',
	'DIGESTS_USER_DIGESTS_NEW_POSTS_ONLY'					=> 'Réglage par défaut pour l\'affichage de nouveaux posts seulement',
	'DIGESTS_USER_DIGESTS_PM_MARK_READ'						=> 'Réglage par défaut pour marquer les messages privés comme lus lorsqu\'ils apparaissent dans le résumé',
	'DIGESTS_USER_DIGESTS_REGISTRATION'						=> 'Réglage par défaut de la possibilité donnée à l\'utlisateur de s\'abonner aux résumés après s\'être enregistré',
	'DIGESTS_USER_DIGESTS_RESET_LASTVISIT'					=> 'Réglage par défaut pour la réinitialisation de la date de dernière visite après l\'envoi d\'un résumé',
	'DIGESTS_USER_DIGESTS_SEND_HOUR_GMT'					=> 'Heure d\'envoi par défaut (UTC)',
	'DIGESTS_USER_DIGESTS_SEND_ON_NO_POSTS'					=> 'Réglage par défaut pour l\'envoi de résumés lorsqu\'il n\'y a pas de nouveaux posts',
	'DIGESTS_USER_DIGESTS_SHOW_FOES'						=> 'Réglage par défaut pour retirer les posts émis par des utilisateurs ignorés',
	'DIGESTS_USER_DIGESTS_SHOW_MINE'						=> 'Réglage par défaut pour retirer les propres posts de l\'utilisateur',
	'DIGESTS_USER_DIGESTS_SHOW_PMS'							=> 'Réglage par défaut pour ajouter des messages privés non lus d\'utilisateurs',
	'DIGESTS_USER_DIGESTS_SORT_ORDER'						=> 'Réglage par défaut de l\'ordre de classement des posts',
	'DIGESTS_USER_DIGESTS_STYLE'							=> 'Réglage par défaut du style de résumé de l\'utilisateur',
	'DIGESTS_USER_DIGESTS_TYPE'								=> 'Réglage par défaut du type de résumé de l\'utilisateur',
	'DIGESTS_USER_DIGESTS_TOC'								=> 'Réglage par défaut de l\'affichage de la table des matières',
	'DIGESTS_USERS_PER_PAGE'								=> 'Abonnés par page',
	'DIGESTS_USERS_PER_PAGE_EXPLAIN'						=> 'Permer de contrôler combien de lignes d\'abonnés au résumé un administrateur peut voir par page lorsqu\'il sélectionne l\'option Éditer les abonnés.',
	'DIGESTS_WEEKLY_DIGESTS_DAY'							=> 'Sélectionnez le jour de la semaine pour envoyer des résumés hebdomadaires',
	'DIGESTS_WITH_SELECTED'									=> 'Avec sélectionné',

));
